export const skills = [
    { language: 'HTML5', image: '/html.svg' },
    { language: 'CSS3', image: '/css.svg' },
    { language: 'Javascript', image: '/javascript.svg' },
    { language: 'Node.js', image: '/node.js.svg' },
    { language: 'React.js', image: '/react.js.svg' },
        { language: 'HTML5', image: '/html.svg' },
    { language: 'CSS3', image: '/css.svg' },
    { language: 'Javascript', image: '/javascript.svg' },
    { language: 'Node.js', image: '/node.js.svg' },
        { language: 'HTML5', image: '/html.svg' },
    { language: 'CSS3', image: '/css.svg' },
    { language: 'Javascript', image: '/javascript.svg' },
    { language: 'Node.js', image: '/node.js.svg' },
        { language: 'HTML5', image: '/html.svg' },
    { language: 'CSS3', image: '/css.svg' },
    { language: 'Javascript', image: '/javascript.svg' },
    { language: 'Node.js', image: '/node.js.svg' },
        { language: 'HTML5', image: '/html.svg' },
    { language: 'CSS3', image: '/css.svg' },
    { language: 'Javascript', image: '/javascript.svg' },
    { language: 'Node.js', image: '/node.js.svg' },
]