
### GET CHAT HISTORY
GET http://localhost:8000/api/ai/history/

### POST CHAT MESSAGE
POST http://localhost:8000/api/ai/message/
Content-Type: application/json

{
    "input": "tell me more about his project, what do you think is the best"
}