
### GET CHAT HISTORY
GET http://portfolio-zi91.onrender.com/api/ai/history/

### POST CHAT MESSAGE
POST http://portfolio-zi91.onrender.com/api/ai/message/
Content-Type: application/json

{
    "input": "tell me more about his project, what do you think is the best"
}

### POST PAGE BLOG
POST http://portfolio-zi91.onrender.com/api/ai/blog/
Content-Type: application/json

{
    "topic": "The Role of AI in Programming"
}

### GET PAGE BLOG
GET http://portfolio-zi91.onrender.com/api/ai/blog/