
### GET CHAT HISTORY
GET http://localhost:8000/api/ai/history/

### POST CHAT MESSAGE
POST http://localhost:8000/api/ai/message/
Content-Type: application/json

{
    "input": "does he know springboot"
}