
### GET ALL REPOSITORY
GET http://portfolio-zi91.onrender.com/api/github/repository/

### GET REPOSITORY
GET http://portfolio-zi91.onrender.com/api/github/repository/BSIT-2DG2-EnrollmentSystem/

### GET CONTRIBUTIONS
GET http://portfolio-zi91.onrender.com/api/github/contributions/